apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.containerName }}-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.image.containerPort }}
  selector:
    app: {{ .Values.image.containerName }}
